-include ../../common/legacy-env-var-support.mk

PROGNAME   := asm-test
COMMON_DIR := $(CHIPCRAFT_SDK_HOME)/common

COMMON_SOURCES := syscalls.c uart.c

CPPFLAGS += -D_ASM_TEST_CODE

include $(COMMON_DIR)/generic.mk
