-include ../../common/legacy-env-var-support.mk

PROGNAME := rtc-test
COMMON_DIR := $(CHIPCRAFT_SDK_HOME)/common

COMMON_SOURCES := syscalls.c uart.c pwd_util.c rtc_util.c

include $(COMMON_DIR)/generic.mk
