-include ../../common/legacy-env-var-support.mk

PROGNAME   := pwd-test
COMMON_DIR := $(CHIPCRAFT_SDK_HOME)/common

COMMON_SOURCES := syscalls.c uart.c core.S core_util.c pwd_util.c

include $(COMMON_DIR)/generic.mk
